# Generated by Django 4.2.19 on 2025-02-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('customer', '0001_initial'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='CustomUser',
        #     new_name='customerUser',
        # ),
    ]
