# Generated by Django 4.2.19 on 2025-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='_id',
            field=models.AutoField(default=123, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
